### PR TITLE
refactor(ALL)

### PR DESCRIPTION
**Pull request by MadLongTom**
Stop using those dumb SQLQUERYCOMMAND and 7ZCMD! If you just wanna use LZMA, using SharpCompress instead.

### CODE REVIEW

**Comment by MadLongTom** [comment]
Publish single file size ~= 15MB (win-x86)

**Comment by Holit** [comment]
very good refactor, make my C# spin.

**Comment by Holit** [comment]
but this project is deprecated.
Using SaveMyGameEx instead, Ex is purely written in C.

**Comment by MadLongTom** [comment]
> but this project is deprecated. Using SaveMyGameEx instead, Ex is purely written in C.

This is disrespectful to dotnet developers

**Pull request merged**
